export class StartListTileConfig {
  showMeeting: boolean = false;
  showAthlete: boolean = false;
  showEvent: boolean = false;
  showStyle: boolean = true;
  showHeat: boolean = true;
  showLane: boolean = true;
  showTimes: boolean = true;
  showRegistrationTime: boolean = true;
  showResults: boolean = true;
  showResultTime: boolean = true;
  showDisqualification: boolean = true;
  showReactionTime: boolean = true;
  showMostSignificantTime: boolean = false;
  laneAsIcon: boolean = false;
  flatStyle: boolean = false;
  allLanes: boolean = false;
  rankStylesIcon: boolean = true;
}
