# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

env:
  NODE_VERSION: 18.x
  CLI_VERSION: 14.2.1

jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm install

  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        Test: [Test,Lint]
    
    needs: install

    steps:
    - uses: actions/checkout@v3
    - name: Test (${{ matrix.Test }})
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm link @angular/cli@${{ env.CLI_VERSION }}
    - if: ${{ matrix.Test == 'Lint' }}
      run: npm test:lint
    - if: ${{ matrix.Test == 'Test' }}
      run: npm test:test
